name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Build the hello-docker Docker image
        run: |
          echo ${{ github.actor }} ${{ secrets.GITHUB_TOKEN }}
          docker build . --tag ghcr.io/publish-to-gcr/hello-docker-gcr-demo:latest
          docker run ghcr.io/publish-to-gcr/hello-docker-gcr-demo:latest
          echo After run ${{ github.actor }}
          docker push ghcr.io/publish-to-gcr/hello-docker-gcr-demo:latest
          echo After push ${{ github.actor }}
